# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1LoginB.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from funciones import *
from PyQt5.QtWidgets import QMessageBox, QWidget

class UIElementsGenerator:
    @staticmethod
    def create_label(parent, geometry, text="", font=None):
        label = QtWidgets.QLabel(parent)
        label.setGeometry(geometry)
        label.setText(text)
        if font:
            label.setFont(font)
        return label

    @staticmethod
    def create_line_edit(parent, geometry):
        line_edit = QtWidgets.QLineEdit(parent)
        line_edit.setGeometry(geometry)
        return line_edit

    @staticmethod
    def create_frame(parent, geometry, style_sheet="", shape=None, shadow=None):
        frame = QtWidgets.QFrame(parent)
        frame.setGeometry(geometry)
        frame.setStyleSheet(style_sheet)
        if shape:
            frame.setFrameShape(shape)
        if shadow:
            frame.setFrameShadow(shadow)
        return frame

    @staticmethod
    def create_push_button(parent, geometry, text="", style_sheet=""):
        button = QtWidgets.QPushButton(parent)
        button.setGeometry(geometry)
        button.setText(text)
        button.setStyleSheet(style_sheet)
        return button

    @staticmethod
    def create_image_label(parent, geometry, image_path):
        label = QtWidgets.QLabel(parent)
        label.setGeometry(geometry)
        label.setPixmap(QtGui.QPixmap(image_path))
        label.setScaledContents(True)
        return label

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 498)

        self.frame = UIElementsGenerator.create_frame(Form, QtCore.QRect(30, 70, 261, 341), "background-color: rgb(255, 107, 39);", QtWidgets.QFrame.WinPanel, QtWidgets.QFrame.Raised)
        self.frame_2 = UIElementsGenerator.create_frame(Form, QtCore.QRect(50, 140, 221, 211), "background-color: rgb(255, 255, 255);", QtWidgets.QFrame.Panel, QtWidgets.QFrame.Raised)
        self.frame_3 = UIElementsGenerator.create_frame(Form, QtCore.QRect(0, 70, 31, 341), "background-color: rgb(255, 255, 255);", QtWidgets.QFrame.WinPanel, QtWidgets.QFrame.Raised)
        
        self.label = UIElementsGenerator.create_image_label(Form, QtCore.QRect(310, 0, 701, 501), "ImagePrincipal.jpeg")
        self.label_2 = UIElementsGenerator.create_image_label(Form, QtCore.QRect(60, 120, 201, 41), "Ministerio.jpg")
        self.label_3 = UIElementsGenerator.create_label(Form, QtCore.QRect(70, 190, 161, 21), "Nombre de Usuario:")
        self.label_4 = UIElementsGenerator.create_label(self.frame_2, QtCore.QRect(20, 110, 161, 21), "Contraseña:")
        self.label_6 = UIElementsGenerator.create_label(self.frame_2, QtCore.QRect(80, 24, 71, 31), "Bienvenido!", QtGui.QFont("Microsoft PhagsPa", 10))
        
        self.lineEdit = UIElementsGenerator.create_line_edit(Form, QtCore.QRect(80, 210, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = UIElementsGenerator.create_line_edit(Form, QtCore.QRect(80, 270, 161, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.pushButton = UIElementsGenerator.create_push_button(self.frame_2, QtCore.QRect(70, 170, 81, 23), "Iniciar Sesión", "background-color: rgb(0, 85, 255); color: white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.validarUsuario)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def validarUsuario(self):
        usuario = self.lineEdit.text().lower().strip()
        contrasena = self.lineEdit_2.text().lower().strip()

        if(not usuario):
            QMessageBox.warning(None, "Error", "El campo de usuario esta vacio")
            return
        
        if(not contrasena):
            QMessageBox.warning(None, "Error", "El campo de contraseña esta vacio")
            return
        

        usuario = ValidarUsuario(usuario, contrasena)
        if(usuario == 0):
            QMessageBox.warning(None, "Error", "El usuario no existe")
            return
        
        if(usuario == 1):
            QMessageBox.warning(None, "Error", "La contraseña es incorrecta")
            return
        
        if(usuario == 2):
            QMessageBox.information(None, "Bienvenido", "El usuario y contraseña son correctos")
            return



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Nombre de Usuario:"))
        self.label_4.setText(_translate("Form", "Contraseña:"))
        self.pushButton.setText(_translate("Form", "Iniciar Sesión"))
        self.label_6.setText(_translate("Form", "Bienvenido!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())