# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1LoginB.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# pip install PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets

# Funciones para configurar los elementos de la interfaz de usuario
def setup_label(parent, text, geometry):
    label = QtWidgets.QLabel(parent)
    label.setGeometry(geometry)
    label.setText(text)
    label.setObjectName("label")
    return label

def setup_lineEdit(parent, geometry):
    lineEdit = QtWidgets.QLineEdit(parent)
    lineEdit.setGeometry(geometry)
    lineEdit.setObjectName("lineEdit")
    return lineEdit

def setup_frame(parent, geometry):
    frame = QtWidgets.QFrame(parent)
    frame.setGeometry(geometry)
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    frame.setObjectName("frame")
    return frame

def create_palette(color):
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(color))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
    return palette

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 498)

        # Llamamos a las funciones para configurar los elementos UI
        self.label_3 = setup_label(Form, "TextLabel", QtCore.QRect(70, 190, 161, 21))
        self.lineEdit = setup_lineEdit(Form, QtCore.QRect(80, 210, 161, 31))
        self.lineEdit_2 = setup_lineEdit(Form, QtCore.QRect(80, 270, 161, 31))
        self.frame = setup_frame(Form, QtCore.QRect(80, 320, 161, 91))

        # Configurar paleta de colores para label_3
        palette = create_palette(QtGui.QColor(255, 0, 0))
        self.label_3.setPalette(palette)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Nombre de Usuario:"))
        self.label_4.setText(_translate("Form", "Contraseña:"))
        self.pushButton.setText(_translate("Form", "Iniciar Sesión"))
        self.label_6.setText(_translate("Form", "Bienvenido!"))



# abrir ui_form
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
